costmap:

    publish_frequency: 0.5
    update_frequency: 0.5

    plugins: 
        - {name: static_map, type: "costmap_2d::StaticLayer"}
        - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
        - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}
    
    # inflation_layer:
        # inflation_radius: 1
        # cost_scaling_factor: 200

    obstacle_layer:
        footprint_clearing_enabled: true
        observation_sources: laser_scan_sensor
        laser_scan_sensor: 
            sensor_frame: laser
            data_type: LaserScan
            topic: /scan
            marking: true
            clearing: true
            inf_is_valid: true

    footprint: [[0.15, 0.1], [0.15, -0.1], [-0.15, -0.1], [-0.15, 0.1]]
    global_frame: /map
    robot_base_frame: base_link