obstacle_range: 6.0
raytrace_range: 6.0
footprint: [[0.15, 0.1], [0.15, -0.1], [-0.15, -0.1], [-0.15, 0.1]]
#robot_radius: ir_of_robot
inflation_radius: 0.3


# plugins: 
#     - {name: static_map,       type: "costmap_2d::StaticLayer"}
#     - {name: obstacle_layer,   type: "costmap_2d::ObstacleLayer"}
#     - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}
    
    #- {name: event_layer,      type: "event_layer::EventLayer"}

update_frequency: 2.0
publish_frequency: 1.0

obstacle_layer:
    footprint_clearing_enabled: false
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}


static_layer:
    subscribe_to_updates: false
