constraint: true
solve_time: 3.0
turning_radius: 0.55
max_dist: 2
# grow_size: 800
limit_time: true
obstacle_resolution: 0.03
base_frame: base_link
update_frequency: 0
publish_tree: false
prediction: false
road_width: 1.0