costmap:
    plugins: 
        - {name: static_map, type: "costmap_2d::StaticLayer"}
        - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}
    
    inflation_layer:
        inflation_radius: 1
        cost_scaling_factor: 200

    footprint: [[-0.1, 0.1], [0.1, 0.1], [0.1, -0.1], [-0.1, -0.1]]