constraint: false
solve_time: 1.0
turning_radius: 0.55
max_dist: 0.5
# grow_size: 800
limit_time: true
obstacle_resolution: 0.03
base_frame: base_link
update_frequency: 0
publish_tree: true
prediction: false
goal_bias: 50
# road_width: 2.0